### PR TITLE
VerticalLinesEffect

### PR DESCRIPTION
**Pull request by kyl3r92**
A new Effect for Activate Power Mode

Vertical lines dash away up- or downwards, depending on upper- and lowercase, or symbols and numbers. 
Spaces create two lines, one upwards, the oder downwards.

see gif here:
http://imgur.com/a/mn4yx

### CODE REVIEW

**Comment by lexcast** [comment]
I really like these effects. I need time to think in the best way to allow packages/users to define their own custom effects and select them. When ready this, effects could be added by another external packages (I don't want to put more effects on the repository, but allow customization) or even for the user, hooking on some events probably.

**Comment by lexcast** [comment]
see #11 and #108 for some attempts to achieve this

**Comment by kyl3r92** [comment]
I read about power-mode a long time ago. For Hacktoberfest 2016, you need 4 Pull Requests on public repos. I saw #11 and thought it might be a good idea to add some more effects.

I didn't expect you to directly merge those, but instead show others what is possible. Reading the last character, reading the position of the cursor etc. So I hope that my work will somehow help to improve the effect aspect. Whatever that will become, an extensible system with an effect-market or just the power mode with another package where you load a bunch of effects at once. Whatever, I am looking forward to watch the developement of this package and atom.io.

**Comment by lexcast** [comment]
hi @kyl3r92 take a look on the #264, your effects could be implemented as a plugins

**Comment by lexcast** [comment]
Closing as now effect can be added with the new service 
https://github.com/JoelBesada/activate-power-mode/wiki/Canvas-effects

**Pull request closed without merging**
