### PR TITLE
Adding 'shake editor' as option

### PR DESCRIPTION
**Pull request by Tushkiz**
implements feature request for #63 and #18

### CODE REVIEW

**Comment by JoelBesada** [comment]
This PR will be included in the 0.4.0 release https://github.com/JoelBesada/activate-power-mode/pull/76. Thank you for your contribution!

**Comment by Tushkiz** [comment]
Sounds great!

**Comment by Tushkiz** [comment]
:+1:

**Comment by birui** [comment]
image

**Pull request closed without merging**
