### PR TITLE
Make effects an extensible/configurable system & add one more effect

### PR DESCRIPTION
**Pull request by chinchang**
Added things:

**New setting for specifying the effect name**
screenshot 2015-12-21 03 09 05

**Extensible system for adding new effects.**
Its as simple as putting a new file in the `effects` folder. And each effect file should export an object with 2 functions: `init` and `update`.
screenshot 2015-12-21 03 11 53

**One more effect of blasting circles**
atom-effect
To get an actual feel -> http://kushagragour.in/code-blast-codemirror/demo/index.html

### CODE REVIEW

**Comment by raulsntos** [comment]
That's a really cool effect, I like the idea of having multiple effects to choose from. Would it be better to make this extendable so that people can write their own effects without having to merge?

**Comment by tejasmanohar** [comment]
:+1: for extensibility

**Comment by tinymins** [comment]
That's cool. I like it :+1:

**Comment by victorperin** [comment]
+1

**Comment by JoelBesada** [comment]
Cool! I agree with @raulsntos on trying to modularize this and allow people to add their own effects without needing to patch the package. We could still include a couple of nice presets to choose from in the package however, and this is a great candidate for that.

I'm a bit busy now during the weekdays, but I'll take a closer look at this later this week.

**Comment by rguanghui** [comment]
:100:

**Comment by crazym** [comment]
like it!!

**Comment by iineva** [comment]
cool!

**Comment by pebble2015** [comment]
+1

**Comment by chinchang** [comment]
Update: Am working on making an extensible system for adding new effects. It would be as simple as adding a new file in a folder. Seems to be coming along well. Just need to see about dynamic configurations in atom.

**Comment by chinchang** [comment]
@JoelBesada Done from my side. Would appreciate your views on the implemented effects system.

**Comment by JoelBesada** [comment]
Hmm, I've looked a bit at the [Atom Services API](http://blog.atom.io/2015/03/25/new-services-API.html) as mentioned by @lexcast in the [0.5.0 PR](https://github.com/JoelBesada/activate-power-mode/pull/78) and I think using that would be nice here.

This means that each effect (except for the default one) would be it's own repository/package and are installed separately. The `activate-power-mode` package could expose a `registerEffect` method that accepts an object with similar `init` and `update` methods that you have here. 

Does that make sense?

**Comment by lexcast** [comment]
Sounds fine for me. I have 3 more effects that I would like to publish.

**Comment by chinchang** [comment]
@JoelBesada Makes sense. Will look into the services API for this if you are not already working on it?

**Comment by JoelBesada** [comment]
I'm not right now, so feel free to take a stab at it if you have the time!

**Comment by lexcast** [comment]
hi @chinchang take a look on the #264 this can be implemented as a plugin effect

**Comment by lexcast** [comment]
Closing as now effect can be added with the new service 
https://github.com/JoelBesada/activate-power-mode/wiki/Canvas-effects

**Pull request closed without merging**
