### PR TITLE
active in all tab & add shake animation switch

### PR DESCRIPTION
**Pull request by faceair**

### CODE REVIEW

**Comment by faceair** [comment]
I‘d prefer to put  the enable switches in the configuration rather than starting manually, so that I can use them in every editor.

**Comment by island205** [comment]
+1

**Comment by tejasmanohar** [comment]
+1

**Comment by cakecatz** [comment]
+1

**Comment by itkang** [comment]
+1

**Comment by victorperin** [comment]
+1

**Comment by mathiasquintero** [comment]
+1

**Comment by huytd** [comment]
+1

**Comment by dsphper** [comment]
My solution is almost the same.
I plan to add music effects

**Comment by jason19659** [comment]
activate-power-mode.coffee:57
Hide Stack Trace
TypeError: Cannot read property 'appendChild' of null
    at Object.module.exports.ActivatePowerMode.setupCanvas (file:///C:/Users/ziywang/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:43:30)
    at Object.module.exports.ActivatePowerMode.subscribeToActiveTextEditor (file:///C:/Users/ziywang/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:35:6)
    at file:///C:/Users/ziywang/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:16:8
    at Emitter.module.exports.Emitter.emit (C:\Users\ziywang\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\ziywang\AppData\Local\atom\app-1.2.4\resources\app.asar\src\pane-container.js:333:27
    at Emitter.module.exports.Emitter.emit (C:\Users\ziywang\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\ziywang\AppData\Local\atom\app-1.2.4\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\ziywang\AppData\Local\atom\app-1.2.4\resources\app.asar\src\pane.js:312:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\ziywang\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:670:19)

**Comment by JoelBesada** [comment]
Thanks! I'll take a closer look at this later this week.

**Comment by huanzhang** [comment]
+1

**Comment by samhax** [comment]
+1

**Comment by JoelBesada** [comment]
This PR will be included in the 0.4.0 release https://github.com/JoelBesada/activate-power-mode/pull/76. Thank you for your contribution!

**Pull request closed without merging**
