### PR TITLE
Rage meter feature

### LINKED ISSUE #55: Add rage bar
We need a "rage bar" :D 
Like each "Enter" or "Backspace" keypress generates "rage", bar fills, when value reaches red zone - effect appears. Rage continiously decreases while idling or reading.

### PR DESCRIPTION
**Pull request by xdjinnx**
This PR fixes #55 

I have added a rage meter requested in this issue: https://github.com/JoelBesada/activate-power-mode/issues/55

I have no previous experiences with Atom packages. Hopefully this PR is good enough!

### CODE REVIEW

**Comment by lexcast** [comment]
I don't know if the rage bar should be on the status bar, moves a lot with the lines/columns counter.
@JoelBesada @nathanchapman what do you think?
Maybe we could replicate the codeinthedark editor combo mode instead

**Comment by A-Manning** [comment]
@lexcast replicating codeinthedark combo mode sounds cool. perhaps rage mode could affect the canvas background? It seems desirable that the rage bar have consistent position, but not get in the way.

**Comment by lexcast** [comment]
Maybe we should wait until have a combo mode, and then improve it with a rage bar.

**Comment by xdjinnx** [comment]
I'm closing this PR because the code is to old. It's easier to rebuild this from scratch.

**Pull request closed without merging**
