### PR TITLE
Added combo system

### PR DESCRIPTION
**Pull request by chatea**
Show the combo text on the top-right corner when input characters continuously.
The combo will be interrupted when deleting non-space character.
(Deleting space is allowed for typesetting reason.)

### CODE REVIEW

**Comment by lexcast** [comment]
hi @chatea can you update this one?

**Comment by chatea** [comment]
okay, but please give me about 1 week.

**Comment by lexcast** [comment]
@chatea there is no rush :smile: Thank you

**Comment by lexcast** [comment]
feature added on #194.
Thank you @chatea

**Pull request closed without merging**
