### PR TITLE
0.4.0

### PR DESCRIPTION
**Pull request by JoelBesada**
This is a work in progress branch for the next version (0.4.0) of the package. This version will include the following things:

- [x] Keep power mode enabled when switching between tabs
- [x] Fix drawing issues after resizing the window
- [x] Power mode can now be toggled off by using the command again
- [x] Screen shake config
- [x] Use the `lighter` composite operation on the canvas for a nicer particle effect
- [x] Particle config

I've merged some of your pull requests into this branch to coordinate everything into one release.

### CODE REVIEW

**Comment by JoelBesada** [comment]
Thanks again for your contributions @faceair, @tinymins, @mrspeaker, @humzashah and @Tushkiz!

**Comment by JoelBesada** [comment]
I'm planning on releasing this tomorrow, unless anything comes up.

**Comment by JoelBesada** [comment]
This fixes https://github.com/JoelBesada/activate-power-mode/issues/2, https://github.com/JoelBesada/activate-power-mode/issues/3, https://github.com/JoelBesada/activate-power-mode/issues/18, https://github.com/JoelBesada/activate-power-mode/issues/29, https://github.com/JoelBesada/activate-power-mode/issues/32, https://github.com/JoelBesada/activate-power-mode/issues/36, https://github.com/JoelBesada/activate-power-mode/issues/42, https://github.com/JoelBesada/activate-power-mode/issues/51, https://github.com/JoelBesada/activate-power-mode/issues/63, and https://github.com/JoelBesada/activate-power-mode/issues/68.

**Comment by faceair** [comment]
Cool! 👍

**Comment by humzashah** [comment]
:+1:

**Comment by danwatco** [comment]
:+1:

**Comment by dlavati** [comment]
:+1:

**Comment by jason19659** [comment]
:+1:

**Pull request merged**
