### PR TITLE
Added sound to power mode.

### PR DESCRIPTION
**Pull request by danwatco**
I've found a simple typewriter sound that I thought would go well.

I've added it in an assets file and have imported it and played it using the Javascript `Audio` class.

### CODE REVIEW

**Comment by alexgleason** [comment]
Related: #21, #28, #38

**Comment by pebble2015** [comment]
+1 like it

**Comment by lexcast** [comment]
hi @danwatco can you update this one?

**Comment by alexgleason** [comment]
Where did the audio files originate? We need to be careful they are licensed properly.

**Comment by danwatco** [comment]
Hi all, I am away currently so don't have time to look into where I got the
files from, I'm home on the 22nd of August so can look into it then.

**Comment by alexgleason** [comment]
They could also be compressed to .mp3 or something with higher compression. I don't think any audiophiles are going to notice a difference in the sound of a clack. :smile:

**Comment by lexcast** [comment]
Feature added on #125 
Thank you @danwatco

**Pull request closed without merging**
