### PR TITLE
[WIP]Cursor position issues

### PR DESCRIPTION
**Pull request by lexcast**
This seems to fix issues with tabs and soft wrap.
It also removes deprecated calls.

I've found these related issues: #4 #8 #39 #47 #59 #66 #80 #85 #91 #96 #110 #127 #131 (there could be more)
And some may be fixed.

### CODE REVIEW

**Comment by lexcast** [comment]
@nathanchapman @JoelBesada Hi, I've been looking for the screenPosition methods, there are for cursor and for buffer, the actual implementation of this PR follows one cursor. But I was thinking about what would be the expected behavior.

* Buffer: Follow every buffer change, even those where is not the cursor, like the trailing whitespace remove on save.
* Cursor: only apply the effect where there are a cursor. can be many cursors.

What do you think about this? I could even put this as a configuration option to select if follows cursor or buffer

**Comment by JoelBesada** [comment]
Following the buffer can probably be a bit confusing since it might not always be clear what's causing a change, like in the case you mentioned with the removed whitespaces on save. So I would vote for always following the cursor, and supporting multiple would be a nice bonus. 

I don't think this should be an option in the configuration though since it's kinda tricky to explain the differences and the default should be good enough either way. But if you think both flavors are worth having then go for it by all means!

**Comment by JoelBesada** [comment]
@lexcast Is this something that we could release in its current state? Since there are so many issues I think it would be nice to get it out.

**Comment by lexcast** [comment]
@JoelBesada We have a dependency on the buffer change, so with the current implementation in this PR, when there is a buffer change that is not related with the cursor, the effect will be displayed on the cursor anyway.
I'm working to display the effect only when the buffer change position matches the cursor position.

**Comment by lexcast** [comment]
My only concern is the performance impact for these checks on positions. 
Also in order to display the effect on all cursors I have to set the throttle wait parameter to 0.

**Comment by JoelBesada** [comment]
Ah, I see. Is there no way to see what triggered the buffer change? 

We should probably try to find a way to not remove the throttling and still support multiple cursors, since if you have a fast key repeat rate and hold down backspace we don't want to completely destroy the frame rate. Is it possible to get the positions of all cursors at the same time?

**Comment by lexcast** [comment]
The didchange event on the buffer is trigger by all text editor changes, remove trailing spaces, typing, etc. Also when there was many buffer changes at the same time, a didchange event is triggered for each.
And yes, is posible to get all cursor positions, but given the way the events are trigger is a bit tricky.

As I see if we have, for example, 4 cursors and type something, 4 didChange events will be triggered, so with the throttling, yes, we are ignoring maybe 3 and process only the first one, we could get all cursor positions and display correctly on multiple cursors. But sometimes the throttling can't avoid ignoring a few of the 3 extra didChange events, so the effects can be render twice (or maybe more) on all 4 cursors.
Maybe is not that important this limitation.

**Comment by JoelBesada** [comment]
Hmm, I think there's another approach that would solve the throttling issues that you mention.

Instead of directly calling the (throttled) `spawnParticles` method from `onChange`, we could push the cursor position (and any other data we might need) onto an array instead. Then we run the `spawnParticle` method separately from `onChange`, for example at a rate of 30 times a second. In that method we loop over 10 or something of the last items in the array to spawn particles from those, and empty the array after that. This way we would have something that resembles the throttling while still being able to create particles from 10 cursors at the same time, or 10 changes from the same cursor during that small time frame. Do you think this could work?

**Comment by lexcast** [comment]
Could work, I guess.
But I'm thinking in another implementation: on `onChange` we throttle the `spawnParticles` but one for each cursor, in this way the effect follow all cursors and we keep the throttling.
But how we throttle spawnParticles for each cursor? Maybe a PowerCursor class with the spawnParticles, so for each new cursor a new PowerCursor. 

Another question is the onChange method async?

**Comment by JoelBesada** [comment]
That makes sense too, if there's a good way identify the different cursors. Not sure about `onChange`, but should be easy enough to test if it is async or not.

**Comment by lexcast** [comment]
There is a event for when a cursor is added (or removed) on the text editor, on this event we do something like:
```coffeescript
@cursors.push(new PowerCursor(cursor))
``` 
and then on `onChange` we check if the buffer change matches a cursor and throttle the PowerCursor.spawnParticles method.

I think this can lead into a refactoring of the package, maybe a PowerCanvas class with the canvas logic.

**Comment by lexcast** [comment]
Also, the easier thing for now should be keep the current implementation (effects follows buffer changes not cursors and with the throttling) just fixing the position on screen. I will do another PR with this fix, and later I will work on the new implementation.

**Comment by lexcast** [comment]
@JoelBesada check out the #139, works well enough. Also the #88 (an auto toggle) has already fixes for crash when no open file #95 and for split panes.
With these two PR merged maybe we could close many issues.

**Comment by JoelBesada** [comment]
Yeah let's get the smaller fixes out first. Are you able to release a new version with the atom package manager as a collaborator, or do I have to run the `apm publish` command to get it out?

**Comment by lexcast** [comment]
Yes, 0.5.0 was released :rocket:

**Comment by JoelBesada** [comment]
@lexcast Awesome! 🎉  🙌

**Pull request closed without merging**
